### ISSUE TITLE
Move my various desktop stuff to this project

### ISSUE THREAD

**Issue by rodlie** [desktopkit/desktopkit#1]

**Comment by rodlie** [comment]
* draco
* qtfm
* powerkit

more ... ?

**Comment by rodlie** [comment]
@probonopd: this project might be of interest for HelloSystem?

I will consolidate most of my unix desktop stuff into one generic support library (and possible tools/apps). And maybe add some more stuff that's needed for a modern desktop in the future.
 
This is not high priority, but I need a "hobby" project for weekends etc.

**Comment by probonopd** [comment]
Hi @rodlie, thanks for the ping. Sent you a PM tweet.

**Comment by rodlie** [comment]
issues for each component has been created, close this.
